### ISSUE TITLE
Have you used Xtext with maven/tycho ?

### ISSUE THREAD

**Issue by paulvi** [skoptelov/jsonclipse#2]
Have you used Xtext with maven/tycho ?

Do you know any bad things about that pairing?

**Comment by skoptelov** [comment]
This project is not using Tycho. 

Overall, in my experience Xtext+Tycho is not a problem. They are orthogonal, since you usually dont want to run Xtext MWE from Maven build.

**Comment by paulvi** [comment]
I don't know Xtext well, so i wondered if switching to tycho could make Xtext development slower.

There is project I tried to revive https://github.com/Nodeclipse/coffeescript-eclipse/
and well tycho does not solve core problems.
